### ISSUE TITLE
Results on the DomainNet.

### ISSUE THREAD

**Issue by Wenlve-Zhou** [JinjingZhu/PMTrans#2]
Thank you so much for the interesting work you've done that has inspired us! We would like to follow up on your work and conduct an experiment to compare. However, we found that there seems to be a problem with your calculation of Avg. on the DomainNet dataset, as the averaged result should be 52.4 instead of 62.9. We hope to hear from you, thank you very much!

**Comment by JinjingZhu** [comment]
Thanks for your comment, I will update the results. Thanks again!
